name: tcc_hugo
description: Projeto de TCC.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  wc_form_validators: ^1.0.0 
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  firebase_core: "^2.14.0"
  firebase_auth: "^4.6.3"
  firebase_messaging: ^14.6.5
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  intl: ^0.18.1
  provider: ^6.0.3
  lottie: ^1.4.2
  chart_sparkline: ^1.0.11
  fl_chart: ^0.36.2
  table_calendar: ^3.0.9
  flutter_local_notifications: ^9.4.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.2.0
  brasil_fields: ^1.10.0
  flutter_onboarding_slider: ^1.0.9
  gallery_saver: ^2.3.2
  # google_maps_flutter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
